services:
  - type: web
    name: scoorpex
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_CREDENTIALS_JSON
      - key: GOOGLE_SHEET_ID
      - key: GOOGLE_DRIVE_FILE_ID_MODELE
