services:
  - type: web
    name: flask-ml-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: GOOGLE_CREDENTIALS_JSON
      - key: GOOGLE_SHEET_ID
      - key: GOOGLE_DRIVE_FILE_ID_MODELE
